version: "3.2"
services:
  mysql:
    image: daxia/dolphin:mysql57
    container_name: mysqlser
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - TZ=Asia/Shanghai
    ports:
      - "33306:3306"
    restart: always
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
  dolphin:
    image: daxia/dolphin:latest
    container_name: dolphin
    links:
      - "dolphin_mysql:mysql_host"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1880:80"
    restart: always
    volumes:
      - type: bind
        source: "./"
        target: "/root/code"